-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Original-Classic")
hl.env("XCURSOR_SIZE", "36")

-- Settings
hl.config({
    decoration = {
        inactive_opacity = 0.8,
        rounding = 4,
        rounding_power = 2.0,
    },
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        gaps_in = 4,
        resize_on_border = true,
    },
    misc = {
        disable_splash_rendering = true,
    },
})
