
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({ output = "DP-1",     mode = "2560x1440@240", position = "0x0",        scale = 1 })
hl.monitor({ output = "DP-2",     mode = "1920x1080@240", position = "auto-right",        scale = 1 })

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
-- Opened in a marker cwd so ~/.bashrc can run fetchit for a new window
-- but not for a split. +new-window talks to the running instance; the
-- fallback covers the case where no Ghostty is running yet.
local ghostty_new_window_dir = "$HOME/.local/state/ghostty/new-window"
local terminal    = "ghostty +new-window --working-directory=" .. ghostty_new_window_dir
                 .. " || ghostty --working-directory=" .. ghostty_new_window_dir
local fileManager = "dolphin"
local menu        = "hyprlauncher"
local browser     = "firefox"
-- The shell's own launcher, not rofi. `qs ipc` talks to the running
-- instance, so this costs no process spawn and the window is styled by the
-- same tokens as the bar.
local app_launcher = "qs ipc -c rd-shell call launcher toggle"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Not swaybg directly any more: the wallpaper switcher (CTRL+ALT+F) writes
    -- whatever you picked to ~/.cache/rd-shell/wallpaper, and --restore puts that
    -- back up and re-runs matugen so the bar comes back the right colour too. It
    -- falls back to rd.png when nothing has been picked yet, so a fresh machine
    -- boots to the same wallpaper this line used to name.
    hl.exec_cmd("~/.config/quickshell/rd-shell/scripts/wallpaper-apply.sh --restore")
    -- The window rules near the bottom pin these to their workspaces on the
    -- second monitor, silently, so booting does not steal focus.
    hl.exec_cmd("vesktop")
    hl.exec_cmd("flatpak run com.spotify.Client")
    hl.exec_cmd("flatpak run org.signal.Signal")
    hl.exec_cmd("tuned-adm profile throughput-performance")
    hl.exec_cmd("wayvibes ~/Documents/Soundpacks/nk-cream -v 2 --mouse ~/Documents/Soundpacks/mp_corsair/ --mouse-volume 0.5 --background")
    hl.exec_cmd("~/.config/quickshell/rd-shell/launch.sh")
    hl.exec_cmd("hyprctl setcursor Bibata-Original-Classic 36")
    -- `hyprpm enable` only marks a plugin as wanted; nothing loads it into a
    -- fresh session but this. Loading one re-parses this file, which is what
    -- lets the plugin_loaded("hyprexpo") block below apply its options.
    hl.exec_cmd("hyprpm reload -n")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

-- The theme too, not just the size: `hyprctl setcursor` below only covers
-- Hyprland's own surfaces, and GTK/Qt apps otherwise draw breeze_cursors.
hl.env("XCURSOR_THEME", "Bibata-Original-Classic")
hl.env("XCURSOR_SIZE", "36")
hl.env("HYPRCURSOR_SIZE", "36")

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("QT_QPA_PLATFORMTHEME", "kde")
-- Anything that looks for a terminal via $TERMINAL first and otherwise falls
-- through a hardcoded list finds kitty before ghostty, which is what used to
-- open kitty from the old rofi launcher.
hl.env("TERMINAL", "/usr/bin/ghostty")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 0,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgb(b86e38)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    -- Grouped windows (tabbed with a group bar) in the palette rather than
    -- Hyprland's yellow defaults. Static caelus values here, the same ones as
    -- the borders above; scripts/wallpaper-apply.sh swaps both for the
    -- matugen colours on every wallpaper switch, in the same eval.
    group = {
        col = {
            border_active   = { colors = {"rgb(b86e38)"}, angle = 45 },
            border_inactive = "rgba(595959aa)",
        },
        groupbar = {
            col = {
                active   = "rgb(b86e38)",
                inactive = "rgba(595959aa)",
            },
        },
    },

    decoration = {
        -- A 4px radius with a plain circular arc (power 2 is a circle, 4 a
        -- squircle): just enough to soften the corners against the bar's
        -- rounded islands without turning tiles into cards.
        rounding       = 4,
        rounding_power = 2,

        -- Forced on every window, whether or not the app has a transparency
        -- setting of its own -- which also means it makes the *contents*
        -- translucent, text included, not just the background the way an
        -- app-side option would. Blur below is what keeps that readable.
        active_opacity   = 0.85,
        inactive_opacity = 0.85,

        -- A fullscreen window has nothing behind it worth seeing, and the
        -- blur would only be sampling black. This is also Hyprland's own
        -- default -- stated here so the two above can be changed without
        -- having to remember that it exists.
        fullscreen_opacity = 1.0,

        -- Dims every unfocused window, so the active one reads as active on
        -- sight instead of only by the border colour above.
        dim_inactive = true,
        dim_strength = 0.25,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        -- Blurs whatever shows through the window opacity set above.
        -- Deliberately a step gentler than the lock screen (hyprlock.conf is
        -- 2 passes at size 8): same passes, smaller radius.
        blur = {
            enabled   = true,
            size      = 6,
            passes    = 2,
            vibrancy  = 0.1696,

            -- Without xray, the bar's own blur (see the quickshell-blur layer
            -- rule below) samples whatever window is directly behind it, so
            -- maximising a window smears its content straight up into the bar.
            -- xray makes it blur past windows to the desktop/wallpaper layer
            -- instead, the same thing xray does for any other blurred layer.
            -- Off. xray makes a blurred layer sample the desktop instead of
            -- the windows under it, which is the textbook setting for a bar
            -- -- and it looks wrong here. The islands are 28% opaque, so with
            -- xray they carry the wallpaper's brightness rather than the
            -- window's, and on a light wallpaper the bar washes out and the
            -- text stops being readable against it. The bar picking up
            -- whatever is actually beneath it is the better-behaved default
            -- on this setup.
            xray = false,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Reapplies the dynamic-colour window border after every parse. The
-- general.col literals just above are set unconditionally every time this
-- file runs, which is what silently reverts a wallpaper-driven border back
-- to the static caelus orange on every `hyprctl reload` -- hyprpm's own
-- reload included. Hyprland's `exec` (unlike `exec-once`, which is what the
-- hl.on("hyprland.start", ...) block below amounts to -- it only fires once,
-- not on every reload) runs on every parse too, so this line, placed right
-- after the literals above, puts the live colour straight back. Safe when
-- dynamic colour is off: the script's --border branch just re-applies these
-- same literals in that case, so this is a no-op either way for a machine
-- that has never touched the wallpaper switcher.
hl.exec_cmd("~/.config/quickshell/rd-shell/scripts/wallpaper-apply.sh --border")

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("snapSlide",      { type = "bezier", points = { {0.19, 1},    {0.22, 1}    } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

-- borderangle is deliberately absent. It repaints the active border's gradient
-- on a timer rather than in response to anything, so it either sweeps forever
-- at the monitor's refresh rate or sweeps once per focus change; neither is
-- information, and the gradient reads the same standing still. `border` below
-- still animates the colour transition when focus actually moves.
hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",     enabled = true, speed = 2.5, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 1.5, bezier = "easeOutQuint", style = "popin 100%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.2, bezier = "linear",       style = "popin 100%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2.5, bezier = "easeOutQuint" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "fadeIn",     enabled = true, speed = 1.5, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",    enabled = true, speed = 1.2, bezier = "almostLinear" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
-- Workspace switch: horizontal slide, snapSlide curve covers most of the
-- distance up front then eases out, so 250 ms reads as smooth but not slow.
-- Previous settings kept here as a backup; full file backup in hyprland.lua.preslide.*.bak
--   hl.animation({ leaf = "workspaces",    enabled = false,  speed = 1.94, bezier = "almostLinear", style = "fade" })
--   hl.animation({ leaf = "workspacesIn",  enabled = false,  speed = 1.21, bezier = "almostLinear", style = "fade" })
--   hl.animation({ leaf = "workspacesOut", enabled = false,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 2.5,  bezier = "snapSlide",    style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 2.5,  bezier = "snapSlide",    style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 2.5,  bezier = "snapSlide",    style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

-- Workspace overview grid, from the hyprexpo plugin:
-- https://github.com/sandwichfarm/hyprexpo (a maintained fork -- upstream
-- hyprwm/hyprland-plugins dropped hyprexpo in 2026-05). Installed with
-- `hyprpm add https://github.com/sandwichfarm/hyprexpo && hyprpm enable
-- hyprexpo`, never bundled with Hyprland, so this must do nothing on a
-- machine that has not run that command.
--
-- hl.config has no dedicated field for plugin settings -- there is no
-- `HL.ConfigOpt.plugin` in the Lua stub -- but it does take a `plugin` key
-- at the top of the table and validate the dotted path underneath it
-- against whatever is currently registered. Confirmed with `hyprctl eval`:
-- before hyprexpo was loaded, `hl.config({ plugin = { hyprexpo = { columns
-- = 3 } } })` failed with "unknown config key 'plugin.hyprexpo.columns'" --
-- the same error a typo'd *core* key gets (tried general.made_up_key_xyz,
-- same shape of error), so this is generic path validation against the live
-- config registry, not a special case that rejects "plugin" outright. That
-- error also does NOT stop the rest of the file from running -- a bind
-- placed right after it in the same eval still registered -- so an
-- unguarded call would have been survivable, just noisy (a config-error
-- toast on every reload until the plugin is installed). The plugin_loaded
-- guard below avoids that noise rather than avoiding a crash.
local function plugin_loaded(name)
    for _, p in ipairs(hl.get_loaded_plugins()) do
        if p.name == name then return true end
    end
    return false
end

if plugin_loaded("hyprexpo") then
    -- Real option names for this fork, enumerated with `hyprctl getoption
    -- plugin:hyprexpo:<name>` against the loaded plugin rather than trusted
    -- from its README (which still lists an `overview_mode` key this build
    -- reports back as "no such option"). All six below came back with a
    -- live default, confirming the name and that hl.config accepts it.
    hl.config({
        plugin = {
            hyprexpo = {
                columns               = 3,
                gaps_in               = 5,   -- matches general.gaps_in above
                gaps_out              = 0,   -- matches general.gaps_out above
                workspace_method      = "center current",
                border_color_current  = "rgb(b86e38)", -- this file's active_border colour;
                                                        -- dropped the 45deg angle, meaningless
                                                        -- on a single flat tile border
                gesture_fingers       = 0,   -- no touchpad device configured in this file;
                                              -- this fork replaced the old enable_gesture
                                              -- bool with a finger count, 0 = off (default)
            },
        },
    })
end

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,de",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = -0.5, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
--
-- Every bind carries a description. SUPER+K lists them (the shell's keybind
-- overview), and it reads them out of `hyprctl binds` — where a Lua bind's dispatcher is the opaque
-- "__lua", so the description is the only thing that can say what it does.
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal), { description = "Terminal (ghostty)" })
local closeWindowBind = hl.bind(mainMod .. " + W", hl.dsp.window.close(), { description = "Close window" })
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("qs ipc -c rd-shell call power toggle"), { description = "Power menu" })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"), { description = "Lock the session" })
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("qs ipc -c rd-shell call notifications toggle"), { description = "Notification panel" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), { description = "File manager (dolphin)" })
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }), { description = "Float / tile window" })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu), { description = "Launcher (hyprlauncher)" })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo(), { description = "Pseudotile window" })
-- Real fullscreen (covers the bar, no gaps). internal = 2 fullscreens the window,
-- client = 0 hides that fact from the app, so Firefox/Chromium keep their tab bar
-- instead of dropping into their own presentation mode.
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen_state({ action = "toggle", internal = 2, client = 0 }), { description = "Fullscreen window" })
-- Fake fullscreen: the window is the only thing on the workspace, but it stops
-- at the bar instead of swallowing it. internal = 1 is Hyprland's maximize,
-- which fills the monitor minus the reserved area the bar already claims --
-- so it lands exactly where a maximized window would, while still hiding
-- everything else the way a real fullscreen does. client = 0 for the same
-- reason as above: the app is never told, so nothing switches itself into a
-- presentation mode over it.
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen_state({ action = "toggle", internal = 1, client = 0 }), { description = "Fake fullscreen (keeps the bar)" })
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), { description = "Toggle split direction" })    -- dwindle only
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser), { description = "Browser (firefox)" })
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(app_launcher), { description = "App launcher" })
-- This cheat sheet. The script reads the descriptions above back out of
-- `hyprctl binds`, so a new bind shows up in it as soon as it is described.
-- The same list inside the bar, with a search field (KeybindOverview.qml).
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("qs ipc -c rd-shell call keybinds toggle"), { description = "Keybind overview (search)" })
-- The system monitor popup, on the key every other desktop opens its task
-- manager with.
hl.bind("CTRL + SHIFT + ESCAPE", hl.dsp.exec_cmd("qs ipc -c rd-shell call system toggle"), { description = "System monitor" })
hl.bind("CTRL + SHIFT + M", hl.dsp.exec_cmd("~/.config/hypr/scripts/mic-toggle.sh"), { description = "Mute / unmute the microphone" })
-- Cycle the keyboard layout (us <-> de). "all" keeps every keyboard on the same
-- layout; switching only the main one leaves the others behind. Hyprland emits
-- activelayout on the event socket, which the bar listens to.
hl.bind("CTRL + SHIFT + SPACE", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"), { description = "Cycle the keyboard layout" })

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { description = "Focus left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "Focus right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { description = "Focus up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { description = "Focus down" })

-- Move active window with mainMod + SHIFT + arrow keys.
-- movewindow only swaps with a window that already sits in that direction, so on
-- a plain side-by-side pair up/down are dead keys. When the pressed axis is empty
-- but the other one is not, flip the dwindle split first: the pair restacks along
-- the pressed axis, each window stretched across the full width (or height), and
-- the move then lands in the freed slot.
local function corners(w)
    local at, size = w.at, w.size
    if type(at) ~= "table" or type(size) ~= "table" then return nil end
    return at.x, at.y, at.x + size.x, at.y + size.y
end

local function has_neighbour(w, direction)
    local ws = w.workspace
    if not ws then return false end
    local x1, y1, x2, y2 = corners(w)
    if not x1 then return false end

    for _, other in ipairs(ws:get_windows()) do
        if other.address ~= w.address and other.mapped and not other.hidden and not other.floating then
            local ox1, oy1, ox2, oy2 = corners(other)
            if ox1 then
                local overlaps_x = ox1 < x2 and ox2 > x1
                local overlaps_y = oy1 < y2 and oy2 > y1
                if direction == "left"  and overlaps_y and ox2 <= x1 then return true end
                if direction == "right" and overlaps_y and ox1 >= x2 then return true end
                if direction == "up"    and overlaps_x and oy2 <= y1 then return true end
                if direction == "down"  and overlaps_x and oy1 >= y2 then return true end
            end
        end
    end
    return false
end

local PERPENDICULAR = {
    left  = { "up", "down" },
    right = { "up", "down" },
    up    = { "left", "right" },
    down  = { "left", "right" },
}

local OPPOSITE = { left = "right", right = "left", up = "down", down = "up" }

local function move_window(direction)
    return function()
        local window = hl.get_active_window()
        local move   = hl.dsp.window.move({ direction = direction })
        if not window or window.floating or window.fullscreen ~= 0
            or has_neighbour(window, direction) then
            hl.dispatch(move)
            return
        end

        local perpendicular = PERPENDICULAR[direction]
        if has_neighbour(window, perpendicular[1]) or has_neighbour(window, perpendicular[2]) then
            hl.dispatch(hl.dsp.layout("togglesplit"))
            local flipped = hl.get_active_window()
            if flipped and has_neighbour(flipped, direction) then
                hl.dispatch(move)
            end
        elseif has_neighbour(window, OPPOSITE[direction]) then
            -- Last window of the row or column: swap back along the axis instead
            -- of letting movewindow hand it to the monitor next door.
            hl.dispatch(hl.dsp.window.move({ direction = OPPOSITE[direction] }))
        end
        -- Otherwise it is the only tiled window, so the press does nothing.
    end
end

hl.bind(mainMod .. " + SHIFT + left",  move_window("left"),  { description = "Move window left" })
hl.bind(mainMod .. " + SHIFT + right", move_window("right"), { description = "Move window right" })
hl.bind(mainMod .. " + SHIFT + up",    move_window("up"),    { description = "Move window up" })
hl.bind(mainMod .. " + SHIFT + down",  move_window("down"),  { description = "Move window down" })
hl.bind("CTRL + ALT + up", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh area"), { description = "Screenshot a region" })
hl.bind("CTRL + ALT + F", hl.dsp.exec_cmd("qs ipc -c rd-shell call wallpaper toggle"), { description = "Wallpaper switcher" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
local MAIN, SECOND = "DP-1", "DP-2"
-- The second monitor owns the workspaces after the main monitor's six, so its
-- Nth workspace is SECOND_WS_BASE + N.
local SECOND_WS_BASE = 6

for i = 1, 6 do
    hl.workspace_rule({
        workspace  = tostring(i),
        monitor    = MAIN,
        default    = (i == 1),
        persistent = true,
    })
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }),      { description = "Workspace " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }), { description = "Move window to workspace " .. i })
end

for j = 1, 4 do
    local ws = SECOND_WS_BASE + j
    hl.workspace_rule({
        workspace  = tostring(ws),
        monitor    = SECOND,
        default    = (j == 1),
        persistent = true,
    })
    hl.bind("CTRL + " .. j,         hl.dsp.focus({ workspace = ws }),      { description = "Workspace " .. ws .. " (second monitor)" })
    hl.bind("CTRL + SHIFT + " .. j, hl.dsp.window.move({ workspace = ws }), { description = "Move window to workspace " .. ws })
end

-- Spotify lives on the third workspace of the second monitor. The window rule
-- near the bottom of this file pins a newly opened window there, so this bind
-- only has to pick between focusing the running client and starting one.
local SPOTIFY_WS = SECOND_WS_BASE + 3
local SIGNAL_WS  = SECOND_WS_BASE + 2
local VESKTOP_WS = SECOND_WS_BASE + 1
hl.bind("CTRL + ALT + S", function()
    if hl.get_window("class:spotify") then
        hl.dispatch(hl.dsp.focus({ window = "class:spotify" }))
    else
        -- Switch first so the workspace is in view while the client starts.
        hl.dispatch(hl.dsp.focus({ workspace = SPOTIFY_WS }))
        hl.dispatch(hl.dsp.exec_cmd("flatpak run com.spotify.Client"))
    end
end, { description = "Spotify on workspace " .. SPOTIFY_WS .. " (second monitor)" })

-- Vesktop lives on the first workspace of the second monitor, same shape as the
-- Spotify bind above: focus the running client, or switch and start one.
hl.bind("CTRL + ALT + V", function()
    if hl.get_window("class:vesktop") then
        hl.dispatch(hl.dsp.focus({ window = "class:vesktop" }))
    else
        hl.dispatch(hl.dsp.focus({ workspace = VESKTOP_WS }))
        hl.dispatch(hl.dsp.exec_cmd("vesktop"))
    end
end, { description = "Vesktop on workspace " .. VESKTOP_WS .. " (second monitor)" })

-- Signal sits on the second workspace of the second monitor.
hl.bind("CTRL + ALT + A", function()
    if hl.get_window("class:org.signal.Signal") then
        hl.dispatch(hl.dsp.focus({ window = "class:org.signal.Signal" }))
    else
        hl.dispatch(hl.dsp.focus({ workspace = SIGNAL_WS }))
        hl.dispatch(hl.dsp.exec_cmd("flatpak run org.signal.Signal"))
    end
end, { description = "Signal on workspace " .. SIGNAL_WS .. " (second monitor)" })

-- Workspace overview (hyprexpo plugin, see the plugin config block above).
-- grave (SUPER + `) was unused in this file and is the upstream default for
-- this plugin's toggle. Under the Lua config the plugin exposes its toggle as
-- hl.plugin.hyprexpo.expo; the legacy `hl.dsp.exec_raw("hyprexpo:expo",
-- "toggle")` still answers "ok" but draws nothing (checked with a screenshot
-- either side), while the Lua call opens the grid. Looked up at press time,
-- not bind time, because this file is parsed once before `hyprpm reload`
-- has loaded the plugin; the guard keeps the key a silent no-op without it.
hl.bind(mainMod .. " + grave", function()
    local expo = hl.plugin and hl.plugin.hyprexpo
    if expo then expo.expo("toggle") end
end, { description = "Workspace overview (hyprexpo)" })

-- The scratchpad special workspace (SUPER+S toggled it, SUPER+SHIFT+S moved a
-- window into it) went unused, so SUPER+SHIFT+S now builds the r/unixporn
-- showcase layout instead.
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("~/.config/quickshell/rd-shell/scripts/showcase.sh"), { description = "Showcase layout (fetchit/btop/cava/yazi)" })

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true, description = "Move window (drag)" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window (drag)" })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true, description = "Mute / unmute" })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("~/.config/hypr/scripts/mic-toggle.sh"),   { locked = true, repeating = true, description = "Mute / unmute the microphone" })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true, description = "Brightness down" })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true, description = "Next track" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play / pause" })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play / pause" })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true, description = "Previous track" })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Floats are small, one-off panels (pickers, confirms, hyprland-run), not
-- docked tiles, so they can afford to arrive differently. A window rule takes
-- `animation` -- the style, not a full "speed bezier style" string; the speed
-- and curve stay with the global `windows` leaf. Floats grow from 85% instead
-- of the global popin, which reads as the panel appearing where you asked for
-- it rather than sliding in from the layout.
hl.window_rule({
    name  = "float-popin",
    match = { float = true },

    animation = "popin 85%",
})

-- dim_inactive is for telling tiles apart; a fullscreen window is the only
-- thing on its monitor, so there is nothing to tell it apart from -- dimming
-- it only darkens a video left playing on the other screen.
hl.window_rule({
    name  = "fullscreen-no-dim",
    match = { fullscreen = true },

    no_dim = true,
})

-- The bar. Its three islands are 80% opaque and the gaps between them are
-- fully transparent, so `ignore_alpha` at 0.2 blurs the plates and leaves the
-- gaps alone -- without it the whole 44px strip would be blurred, including
-- the wallpaper showing through above and below the islands. `blur_popups`
-- covers the cards the bar hangs under its pills. The wallpaper sits on its
-- own `qs-wallpaper` layer and must never match this, hence the anchored
-- pattern rather than a prefix.
hl.layer_rule({
    name  = "quickshell-blur",
    match = { namespace = "^quickshell$" },

    blur         = true,
    blur_popups  = true,
    ignore_alpha = 0.2,
})

-- The OSDs -- volume, microphone, brightness, keyboard layout. Each is its own
-- layer surface with its own namespace, so the bar's rule above (anchored to
-- `^quickshell$` on purpose, to keep the wallpaper layer out) does not reach
-- them. Same treatment for the same reason: the card is translucent, so
-- without blur it shows whatever window it landed on straight through, and a
-- status card over a text editor is unreadable in a way the bar never is.
-- `ignore_alpha` is higher than the bar's 0.2 because there are no fully
-- transparent gaps to protect here, only the rounded corners.
hl.layer_rule({
    name  = "quickshell-osd-blur",
    match = { namespace = "^qs-(audioosd|brightnessosd|contrastosd|kbosd|launcher|keybinds)$" },

    blur         = true,
    ignore_alpha = 0.2,
})

-- Every popup a bar pill opens -- audio, mic, network, calendar,
-- notifications, disk, media, the Claude panel, dzuma, settings, the system
-- monitor, the power menu, the toast stack, and BarPopup's own default
-- namespace for anything that does not set its own -- is a `PanelWindow` on
-- its own layer, so neither rule above reaches it: the first is anchored to
-- `^quickshell$` (the bar itself), the second to the four OSDs. The
-- wallpaper switcher (`qs-wallpapers`) gets the same treatment, since it is
-- chrome floating over the desktop the same as any other popup. `qs-wallpaper`
-- (singular) is deliberately left out of the list -- that is the wallpaper
-- layer itself, and blurring it would blur the background into itself, hence
-- the anchored alternation rather than a `qs-wallpaper` prefix that would
-- catch both. Same `ignore_alpha` as the OSDs: these cards have no fully
-- transparent gaps to protect, only rounded corners.
hl.layer_rule({
    name  = "quickshell-popup-blur",
    match = { namespace = "^qs-(audio|calendar|claude|disk|dzuma|edge|media|mic|network|notifications|popup|popups|power|settings|sysmon|wallpapers)$" },

    blur         = true,
    ignore_alpha = 0.2,
})

-- The desktop layer (giant clock + now-playing card, DesktopWidgets.qml,
-- namespace qs-desktop) deliberately gets NO blur rule: the card is meant to
-- be see-through, and a blurred backdrop turns its low-alpha body into a
-- solid-looking frosted slab that hides the wallpaper it sits on.

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Spotify always opens on the second monitor's third workspace, whether it was
-- started by CTRL+ALT+S, from a launcher or at boot. "silent" keeps the boot-time
-- launch from dragging focus away; the bind focuses the workspace itself.
hl.window_rule({
    name  = "spotify-workspace",
    match = { class = "^spotify$" },

    workspace = SPOTIFY_WS .. " silent",
})

-- Vesktop is started at launch (see the exec_cmd block at the top) and lands on
-- the second monitor's first workspace. "silent" so the boot-time launch does
-- not drag focus off the main monitor.
hl.window_rule({
    name  = "vesktop-workspace",
    match = { class = "^vesktop$" },

    workspace = VESKTOP_WS .. " silent",
})

-- Signal, same deal: pinned to the second monitor's second workspace and silent
-- so the boot-time launch stays out of the way.
hl.window_rule({
    name  = "signal-workspace",
    match = { class = "^org.signal.Signal$" },

    workspace = SIGNAL_WS .. " silent",
})

-- HyprMod managed settings
require("hyprland-gui")
