general {
    lock_cmd = loginctl lock-session
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 2
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn the displays off after 10 minutes
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

